################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../Src/arm_fir_decimate_init_q15.c \
../Src/arm_fir_decimate_q15.c \
../Src/audio_application.c \
../Src/cube_hal_f4.c \
../Src/dma.c \
../Src/gpio.c \
../Src/main.c \
../Src/sai.c \
../Src/stm32xx_it.c \
../Src/syscalls.c \
../Src/sysmem.c \
../Src/system_stm32f4xx.c \
../Src/usart.c \
../Src/usbd_audio_if.c \
../Src/usbd_conf_f4.c \
../Src/usbd_desc.c 

OBJS += \
./Src/arm_fir_decimate_init_q15.o \
./Src/arm_fir_decimate_q15.o \
./Src/audio_application.o \
./Src/cube_hal_f4.o \
./Src/dma.o \
./Src/gpio.o \
./Src/main.o \
./Src/sai.o \
./Src/stm32xx_it.o \
./Src/syscalls.o \
./Src/sysmem.o \
./Src/system_stm32f4xx.o \
./Src/usart.o \
./Src/usbd_audio_if.o \
./Src/usbd_conf_f4.o \
./Src/usbd_desc.o 

C_DEPS += \
./Src/arm_fir_decimate_init_q15.d \
./Src/arm_fir_decimate_q15.d \
./Src/audio_application.d \
./Src/cube_hal_f4.d \
./Src/dma.d \
./Src/gpio.d \
./Src/main.d \
./Src/sai.d \
./Src/stm32xx_it.d \
./Src/syscalls.d \
./Src/sysmem.d \
./Src/system_stm32f4xx.d \
./Src/usart.d \
./Src/usbd_audio_if.d \
./Src/usbd_conf_f4.d \
./Src/usbd_desc.d 


# Each subdirectory must supply rules for building sources it contributes
Src/arm_fir_decimate_init_q15.o: ../Src/arm_fir_decimate_init_q15.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 -DSTM32F446xx -DUSE_HAL_DRIVER -DUSE_STM32F4XX_NUCLEO -DUSE_USB_FS -c -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Inc" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Middlewares/ST/STM32_Audio/Addons/PDM/Inc" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Middlewares/ST/STM32_USB_Device_Library/Class/AUDIO/Inc" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/BSP/CCA02M1" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/BSP/Components/Common" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/BSP/STM32F4xx-Nucleo" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/CMSIS/Core/Include" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/CMSIS/DSP/Include" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/CMSIS/Include" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/STM32F4xx_HAL_Driver/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/arm_fir_decimate_init_q15.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/arm_fir_decimate_q15.o: ../Src/arm_fir_decimate_q15.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 -DSTM32F446xx -DUSE_HAL_DRIVER -DUSE_STM32F4XX_NUCLEO -DUSE_USB_FS -c -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Inc" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Middlewares/ST/STM32_Audio/Addons/PDM/Inc" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Middlewares/ST/STM32_USB_Device_Library/Class/AUDIO/Inc" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/BSP/CCA02M1" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/BSP/Components/Common" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/BSP/STM32F4xx-Nucleo" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/CMSIS/Core/Include" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/CMSIS/DSP/Include" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/CMSIS/Include" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/STM32F4xx_HAL_Driver/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/arm_fir_decimate_q15.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/audio_application.o: ../Src/audio_application.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 -DSTM32F446xx -DUSE_HAL_DRIVER -DUSE_STM32F4XX_NUCLEO -DUSE_USB_FS -c -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Inc" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Middlewares/ST/STM32_Audio/Addons/PDM/Inc" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Middlewares/ST/STM32_USB_Device_Library/Class/AUDIO/Inc" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/BSP/CCA02M1" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/BSP/Components/Common" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/BSP/STM32F4xx-Nucleo" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/CMSIS/Core/Include" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/CMSIS/DSP/Include" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/CMSIS/Include" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/STM32F4xx_HAL_Driver/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/audio_application.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/cube_hal_f4.o: ../Src/cube_hal_f4.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 -DSTM32F446xx -DUSE_HAL_DRIVER -DUSE_STM32F4XX_NUCLEO -DUSE_USB_FS -c -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Inc" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Middlewares/ST/STM32_Audio/Addons/PDM/Inc" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Middlewares/ST/STM32_USB_Device_Library/Class/AUDIO/Inc" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/BSP/CCA02M1" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/BSP/Components/Common" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/BSP/STM32F4xx-Nucleo" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/CMSIS/Core/Include" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/CMSIS/DSP/Include" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/CMSIS/Include" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/STM32F4xx_HAL_Driver/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/cube_hal_f4.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/dma.o: ../Src/dma.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 -DSTM32F446xx -DUSE_HAL_DRIVER -DUSE_STM32F4XX_NUCLEO -DUSE_USB_FS -c -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Inc" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Middlewares/ST/STM32_Audio/Addons/PDM/Inc" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Middlewares/ST/STM32_USB_Device_Library/Class/AUDIO/Inc" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/BSP/CCA02M1" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/BSP/Components/Common" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/BSP/STM32F4xx-Nucleo" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/CMSIS/Core/Include" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/CMSIS/DSP/Include" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/CMSIS/Include" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/STM32F4xx_HAL_Driver/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/dma.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/gpio.o: ../Src/gpio.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 -DSTM32F446xx -DUSE_HAL_DRIVER -DUSE_STM32F4XX_NUCLEO -DUSE_USB_FS -c -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Inc" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Middlewares/ST/STM32_Audio/Addons/PDM/Inc" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Middlewares/ST/STM32_USB_Device_Library/Class/AUDIO/Inc" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/BSP/CCA02M1" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/BSP/Components/Common" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/BSP/STM32F4xx-Nucleo" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/CMSIS/Core/Include" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/CMSIS/DSP/Include" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/CMSIS/Include" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/STM32F4xx_HAL_Driver/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/gpio.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/main.o: ../Src/main.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 -DSTM32F446xx -DUSE_HAL_DRIVER -DUSE_STM32F4XX_NUCLEO -DUSE_USB_FS -c -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Inc" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Middlewares/ST/STM32_Audio/Addons/PDM/Inc" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Middlewares/ST/STM32_USB_Device_Library/Class/AUDIO/Inc" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/BSP/CCA02M1" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/BSP/Components/Common" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/BSP/STM32F4xx-Nucleo" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/CMSIS/Core/Include" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/CMSIS/DSP/Include" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/CMSIS/Include" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/STM32F4xx_HAL_Driver/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/main.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/sai.o: ../Src/sai.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 -DSTM32F446xx -DUSE_HAL_DRIVER -DUSE_STM32F4XX_NUCLEO -DUSE_USB_FS -c -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Inc" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Middlewares/ST/STM32_Audio/Addons/PDM/Inc" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Middlewares/ST/STM32_USB_Device_Library/Class/AUDIO/Inc" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/BSP/CCA02M1" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/BSP/Components/Common" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/BSP/STM32F4xx-Nucleo" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/CMSIS/Core/Include" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/CMSIS/DSP/Include" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/CMSIS/Include" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/STM32F4xx_HAL_Driver/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/sai.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/stm32xx_it.o: ../Src/stm32xx_it.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 -DSTM32F446xx -DUSE_HAL_DRIVER -DUSE_STM32F4XX_NUCLEO -DUSE_USB_FS -c -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Inc" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Middlewares/ST/STM32_Audio/Addons/PDM/Inc" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Middlewares/ST/STM32_USB_Device_Library/Class/AUDIO/Inc" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/BSP/CCA02M1" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/BSP/Components/Common" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/BSP/STM32F4xx-Nucleo" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/CMSIS/Core/Include" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/CMSIS/DSP/Include" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/CMSIS/Include" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/STM32F4xx_HAL_Driver/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/stm32xx_it.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/syscalls.o: ../Src/syscalls.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 -DSTM32F446xx -DUSE_HAL_DRIVER -DUSE_STM32F4XX_NUCLEO -DUSE_USB_FS -c -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Inc" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Middlewares/ST/STM32_Audio/Addons/PDM/Inc" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Middlewares/ST/STM32_USB_Device_Library/Class/AUDIO/Inc" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/BSP/CCA02M1" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/BSP/Components/Common" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/BSP/STM32F4xx-Nucleo" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/CMSIS/Core/Include" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/CMSIS/DSP/Include" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/CMSIS/Include" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/STM32F4xx_HAL_Driver/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/syscalls.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/sysmem.o: ../Src/sysmem.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 -DSTM32F446xx -DUSE_HAL_DRIVER -DUSE_STM32F4XX_NUCLEO -DUSE_USB_FS -c -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Inc" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Middlewares/ST/STM32_Audio/Addons/PDM/Inc" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Middlewares/ST/STM32_USB_Device_Library/Class/AUDIO/Inc" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/BSP/CCA02M1" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/BSP/Components/Common" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/BSP/STM32F4xx-Nucleo" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/CMSIS/Core/Include" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/CMSIS/DSP/Include" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/CMSIS/Include" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/STM32F4xx_HAL_Driver/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/sysmem.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/system_stm32f4xx.o: ../Src/system_stm32f4xx.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 -DSTM32F446xx -DUSE_HAL_DRIVER -DUSE_STM32F4XX_NUCLEO -DUSE_USB_FS -c -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Inc" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Middlewares/ST/STM32_Audio/Addons/PDM/Inc" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Middlewares/ST/STM32_USB_Device_Library/Class/AUDIO/Inc" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/BSP/CCA02M1" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/BSP/Components/Common" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/BSP/STM32F4xx-Nucleo" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/CMSIS/Core/Include" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/CMSIS/DSP/Include" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/CMSIS/Include" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/STM32F4xx_HAL_Driver/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/system_stm32f4xx.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/usart.o: ../Src/usart.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 -DSTM32F446xx -DUSE_HAL_DRIVER -DUSE_STM32F4XX_NUCLEO -DUSE_USB_FS -c -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Inc" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Middlewares/ST/STM32_Audio/Addons/PDM/Inc" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Middlewares/ST/STM32_USB_Device_Library/Class/AUDIO/Inc" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/BSP/CCA02M1" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/BSP/Components/Common" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/BSP/STM32F4xx-Nucleo" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/CMSIS/Core/Include" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/CMSIS/DSP/Include" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/CMSIS/Include" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/STM32F4xx_HAL_Driver/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/usart.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/usbd_audio_if.o: ../Src/usbd_audio_if.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 -DSTM32F446xx -DUSE_HAL_DRIVER -DUSE_STM32F4XX_NUCLEO -DUSE_USB_FS -c -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Inc" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Middlewares/ST/STM32_Audio/Addons/PDM/Inc" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Middlewares/ST/STM32_USB_Device_Library/Class/AUDIO/Inc" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/BSP/CCA02M1" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/BSP/Components/Common" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/BSP/STM32F4xx-Nucleo" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/CMSIS/Core/Include" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/CMSIS/DSP/Include" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/CMSIS/Include" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/STM32F4xx_HAL_Driver/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/usbd_audio_if.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/usbd_conf_f4.o: ../Src/usbd_conf_f4.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 -DSTM32F446xx -DUSE_HAL_DRIVER -DUSE_STM32F4XX_NUCLEO -DUSE_USB_FS -c -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Inc" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Middlewares/ST/STM32_Audio/Addons/PDM/Inc" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Middlewares/ST/STM32_USB_Device_Library/Class/AUDIO/Inc" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/BSP/CCA02M1" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/BSP/Components/Common" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/BSP/STM32F4xx-Nucleo" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/CMSIS/Core/Include" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/CMSIS/DSP/Include" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/CMSIS/Include" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/STM32F4xx_HAL_Driver/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/usbd_conf_f4.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/usbd_desc.o: ../Src/usbd_desc.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 -DSTM32F446xx -DUSE_HAL_DRIVER -DUSE_STM32F4XX_NUCLEO -DUSE_USB_FS -c -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Inc" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Middlewares/ST/STM32_Audio/Addons/PDM/Inc" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Middlewares/ST/STM32_USB_Device_Library/Class/AUDIO/Inc" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/BSP/CCA02M1" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/BSP/Components/Common" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/BSP/STM32F4xx-Nucleo" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/CMSIS/Core/Include" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/CMSIS/DSP/Include" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/CMSIS/Include" -I"C:/Users/10007069/code/USB_AUDIO/MEMS_RECORDER/Drivers/STM32F4xx_HAL_Driver/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/usbd_desc.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

